// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://avodqajneytxiarbjrcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2b2RxYWpuZXl0eGlhcmJqcmNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MzQxNDUsImV4cCI6MjA3ODExMDE0NX0.-mx1W_s2rSsVMqm8SFSDli4kFJaqlYmqqwaX7gS5Fto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);